server:
  port: 8081

spring:
  # 配置spring data jpa
  jpa:
    generate-ddl: true # 指定是否在spring容器启动时创建表，默认false
    show-sql: true # 指定在控制台是否显示SQL语句，默认false

    hibernate:
      ddl-auto: none # 指定应用重启后不重新更新表内容
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///mysql1?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 68731182
#指定微服务名称
  application:
    name: abcmsc-provider-depart

#客户端指定连接服务端地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: abcmsc-provider-depart-8081
    #设置服务器向注册中心发送一次心跳时间:秒
    lease-renewal-interval-in-seconds: 1
    #注册中心认为服务的失效时间,失效后剔除服务:秒
    lease-expiration-duration-in-seconds: 3
#复杂配置
#eureka:
#  client:
#    #指定区域
#    region: xxx
#    #指定区域中包含的地带zone
#    availability-zones:
#      xxx: aaa, bbb
#    service-url:
#      aaa: http://localhost:8000/eureka
#      bbb: http://localhost:8000/eureka
#    #指定要连接的注册中心的所在区域
#    fetch-remote-regions-registry: xxx
info:
  auth: Author
  app.name: name
  company.name: www.baidu.com
  company.addr: 天津市静海区
# 配置日志
logging:
  pattern:
    console: level-%level %msg%n

  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # 在show-sql为true时显示SQL中的动态参数值
    org.hibernate.hql.internal.ast.exec.BasicExecutor: trace # 在show-sql为true时显示查询结果
    com.abc: debug

