server:
  port: 8080

#注册服务
spring:
  application:
    name: abcmsc-consumer-depart
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
#配置服务上下线
management:
  #开启监控终端
  endpoints:
    web:
      exposure:
        include: "*"
  #开启shutdown监控 等于关闭服务器 服务下架
  endpoint:
    shutdown:
      enabled: true
#设置Feign代理客户端属性
feign:
  client:
    default:
         connectTimeout: 5000 #feign客户端连接提供者的超时时间
         readTimeout: 5000   #feign客户端在连接上客户端后,向提供者提交请求的超时时间
  #开启对hystrix的支持
  hystrix:
    enabled: true

  compression:
    request:
      enabled: true           #请求压缩
      mime-types: text/xml,application/xml,application/json  #请求类型
      min-request-size: 2048   #请求文件大小  超过2048进行压缩
    response:
      enabled: true        #响应压缩
      mime-types: text/xml,application/xml,application/json  #请求类型
      min-request-size: 2048   #请求文件大小  超过2048进行压缩
# 修改负载均衡策略为：随机策略
#abcmsc-provider-depart:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000