server:
  port: 8300
eureka:
  client:
    register-with-eureka: false # 指定当前主机是否需要向Eureka Server注册自己
    fetch-registry: false       # 指定当前主机是否需要从Eureka Server下载服务注册表
    service-url:
      #当前Eureka Server对外暴露的服务地址
      defaultZone: http://eureka8100.com:8100/eureka,http://eureka8200.com:8200/eureka,http://eureka8300.com:8300/eureka
  instance:
    hostname: eureka8300


